### ISSUE TITLE
z-ordering of breeds

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/Galapagos#115]
when I run http://ccl.northwestern.edu/devel/ClimateChange/climatechange.html I see turtles sometimes going in front of the clouds, sometimes going behind them

this seems to indicate that the Galapagos renderer isn't handling z-order the same as the JVM NetLogo renderer.

the correct order is: sort first by breed, in declaration order. within each breed, sort by who number.

**Comment by LaCuneta** [comment]
The [fix for this](https://github.com/NetLogo/Galapagos/commit/ac55776a93cf0055b2944262937092177a379c8a) is now live.
