### ISSUE TITLE
Unify look and feel across browsers

### ISSUE THREAD

**Issue by frankduncan** [NetLogo/Galapagos#133]
From TheBizzle:

> but another thing that should be addressed before the merge is adding some CSS to the widgets to make them look consistent across browsers. This is something that Dan and I recently talked about, and he found it bothersome that the UIs difficult to modify, thanks to changes showing up differently in different browsers.

**Comment by TheBizzle** [comment]
As far as I'm concerned, this was fixed in a422b6dac6a0e96ed641741d2e2077c5b180a090 when the `/tortoise` page was introduced.
