### ISSUE TITLE
Update slider values when other sliders affect them

### ISSUE THREAD

**Issue by frankduncan** [NetLogo/Galapagos#135]
From @qiemem in #117 

> Sliders update their max and min properly when other sliders affect them. However, they don't update max, min, or value properly when just regular netlogo code affects them. This is fairly minor I think, so I'd be okay with just opening this as a bug.

**Comment by TheBizzle** [comment]
This is fixed—I believe by a422b6dac6a0e96ed641741d2e2077c5b180a090.
