### ISSUE TITLE
Pen trails should be drawn

### ISSUE THREAD

**Issue by TheBizzle** [NetLogo/Galapagos#139]
Doing `crt 1 [ pen-down fd 10 ]` should create a turtle, move it, and have it leave a trail behind it.  There's support for this in the engine/updater (pen-related keys that go into the updates for turtles are `"PEN-MODE"`, `"PEN-SIZE"`, and `"COLOR"`), but the pen trail isn't drawn.

@dweintrop is working on his Blockly-related project that leverages Tortoise, and he wants his turtle(s) to be able to leave trails behind them.  The renderer needs to support this soon enough, anyway, so I think we should just do it now.

**Comment by qiemem** [comment]
Hmm, I think this means that updates can't be squashed on the engine side while the pen is down, since we can't have the speed slider dictate how sparsely paths are drawn. That is, a new update must be fired off every time a turtle moves when the pen is down. Otherwise, when the speed slider is high, turtles could move a lot before any lines are drawn.

**Comment by TheBizzle** [comment]
You're right.  And that seems problematic.  Might it make more sense to just track the pen state in the engine?

**Comment by SethTisue** [comment]
I think the engine already emits drawing events, similarly to how plotting events are emitted?

**Comment by qiemem** [comment]
@TheBizzlem, what do you think of using drawing events like that here as well?

**Comment by TheBizzle** [comment]
I think that sounds favorable, but it's not clear how we should implement this event system.  The idea of events bubbling up from the engine over to the renderer seem like a good design to me, and it's not clear to me whether or not that's what's being proposed.  Or is the idea that just add another entry to the updates that the engine generates—this one with a key for each of the actions in the file Seth linked, and each key associated with list of action objects?  That strikes me as a good solution.  Or am I totally missing what you guys are going for?

Maybe it would be worth hooking things up to be able to handle the drawing events coming out of JVM NetLogo by first getting Beak working with Teletortoise on this?

**Comment by SethTisue** [comment]
I don't think I have any special insight into this. It isn't obvious to me whether drawing and/or plotting events should be folded into the existing engine updates, or be a separate stream somehow.

**Comment by qiemem** [comment]
I was thinking add it to the updates like so:

`{turtles: ..., patches: ..., drawEvents: [...]}`

where `drawEvents` contains objects of the form:

`{type: "line", x1: 0, y1: 0, x2: 5, y2: 3}`

or something like that.

Updates would then still be composable by concatenating the events list.

**Comment by TheBizzle** [comment]
Okay, that makes sense.

**Comment by TheBizzle** [comment]
@mrerrormessage 

As you know, the branch for this in Headless is [here](https://github.com/NetLogo/NetLogo-Headless/tree/wip-drawing-mirroring), and it's most of the way to completion.

There is also partially-completed Tortoise branch [here](https://github.com/NetLogo/Tortoise/tree/wip-drawing-events), which I think covers all of the drawing that the Tortoise engine currently knows how to do.  However, I don't expect the tests to pass when this branch is hooked up to an enhanced version of Headless, because Headless' updates for drawing stuff involves arrays of bytes, and the Tortoise engine doesn't generate those (and shouldn't).  I think the docking tests in Tortoise will need to throw out (or otherwise not look at) the `imageBytes` value.

After that, if the tests look good, it will be time for someone over here in Galapagos to do something about actually rendering the updates.

**Comment by TheBizzle** [comment]
The Tortoise artifact with SHA `4ec73a4` (just made available) outputs update objects with a `drawingEvents` array that contains events turtle stamps, link stamps, and pen trails.

Here are the events that currently exist:

```
{ type: "clear-drawing" }

{ type: "line", fromX, fromY, toX, toY, rgb, size, penMode }

{ type: "stamp-image", agentType: "turtle", stamp: {x, y, size, heading, color, shapeName} }

{ type: "stamp-image", agentType: "link", stamp: {x1, y1, x2, y2, midpointX, midpointY, heading, color, shapeName, thickness} }
```

`penMode` can be `"up"`, `"down"`, or `"erase"`.  I believe that the colors are RGB lists.

**Comment by qiemem** [comment]
Ok, erasing should now work. Note that stamp events need a `stampMode` added, which should be set to `"erase"` for a stamp-erase.

**Comment by SethTisue** [comment]
:fireworks:
