### ISSUE TITLE
Support `follow`/`ride` in Beak

### ISSUE THREAD

**Issue by TheBizzle** [NetLogo/Galapagos#154]
As of 9e5f6680f6fa4083a27ff5801adc98e8d16384fb, `ride` and `follow` are supported in the Tortoise engine.  The difference between them only comes up in the 3D View (which we don't have at the moment), so they can both be treated the same for now.

In the updates, you can watch `observer[0].perspective` and `observer[0].targetAgent` for the relevant information about perspectives.  Here are the meanings of the possible `perspective` values:

  * 0
    * Observe (normal)
  * 1
    * Ride (keep target agent in the center of the View)
  * 2
    * Follow (same as Ride, except when done in 3D View)
  * 3
    * Watch (highlight target agent, but keep View focused on its original center)

Here are the meanings of the possible `targetAgent` values:

  * `null`:
    * No target agent
  * `[1, tid]`
    * Focus on the turtle with the `id` `tid`
  * `[2, pid]`
    * Focus on the patch with the `id` `pid`
  * Anything else
    * Invalid state

**Comment by qiemem** [comment]
Good model for testing follow: https://gist.github.com/qiemem/80bdf3da15ae83645a4d
