### ISSUE TITLE
Support vertical sliders

### ISSUE THREAD

**Issue by qiemem** [NetLogo/Galapagos#171]
I set this to low priority since vertical sliders are pretty rare. @TheBizzle, if you disagree, feel free to toss the label.

**Comment by Idloj** [comment]
![approved](https://cloud.githubusercontent.com/assets/8083458/8474092/b66bdd74-20b6-11e5-8fa3-c15c4092559a.gif)
Sorry I didn't make it explode at the end, but at least it's animated.

**Comment by TheBizzle** [comment]
:+1:

**Comment by TheBizzle** [comment]
It occurred to me just now that this is pretty simple to implement.  Playing around with it in-browser with the developer tools for a few of minutes, it looks like the solution should just be to change the style of the slider's `label` to include `transform: rotate(-90deg) translate(<x>px, <y>px);` (where `<x>` and `<y>` are some computed values that are not yet fully apparent to me).

It would be nice to use the `transform-origin` CSS property for handling the translation, but it's currently only included in a working draft of the spec, so a `translate` is probably the best option for now.

**Comment by LaCuneta** [comment]
Completed by Adam [here](https://github.com/NetLogo/Galapagos/commit/69cbf12031d7dc067f3bb5c5a0acda8edee83fec).
