### ISSUE TITLE
There should be a way to create a new, blank model

### ISSUE THREAD

**Issue by TheBizzle** [NetLogo/Galapagos#191]
It's kind of annoying that the `/tortoise` URL forces you to work within the framework on an already-existing NetLogo model.  It would be nice you could get a clean slate (like "File" => "New" in desktop NetLogo).

**Comment by CamdenClark** [comment]
Would it be okay to simply have a blank model (the .nlogo file from saving File -> New in netlogo) in the models library?

**Comment by TheBizzle** [comment]
I'm not sure whether or not that's the best way for this to look in its final form, but it would definitely be a good starting point, either way.

**Comment by venky18** [comment]
@TheBizzle  i would like to work on this

**Comment by CamdenClark** [comment]
Just to get started on this.
https://github.com/NetLogo/Galapagos/pull/360

**Comment by CamdenClark** [comment]
@TheBizzle I'm not too sure about this functionality--I'm at an impasse. Either I have a really long .nlogo string just dumped into a coffee file somewhere or I have a separate .nlogo file that lives in the models library folder but isn't added to the one that's visible to users.

What do you think?

**Comment by TheBizzle** [comment]
The long `.nlogo` string in a CoffeeScript file doesn't bother me, as long as that file is solely about this "new model" functionality.
