### ISSUE TITLE
Tortoise should allow the saving and loading of files through local storage

### ISSUE THREAD

**Issue by TheBizzle** [NetLogo/Galapagos#193]
It's pretty fundamental for Tortoise authoring to allow people to save and load their models.  As a basic (and relatively easy) step towards achieving that, let's use HTML's [local storage](http://diveintohtml5.info/storage.html) to get something in place.

See #189 for related discussion.

**Comment by skorlir** [comment]
Here's a nice looking API wrapper for localStorage that could make this easier/more fun: https://github.com/dkraczkowski/collection.js

**Comment by TheBizzle** [comment]
I'm reconsidering the value of this proposal.  It made sense to me at the time it was submitted, but I feel that, now that we can export `.nlogo` files from the browser, maybe this is really just an anti-feature, given that such a thing would make it harder for the user to distribute their model to others or open their model in desktop NetLogo.

Opinions?

**Comment by TheBizzle** [comment]
I gathered some opinions in-person.  People seem feel similarly to me on this matter, so I'm going to close this as "invalid".  If someone makes a strong argument for why we should support this, I can be convinced to reopen the ticket.

**Comment by SethTisue** [comment]
agree
