### ISSUE TITLE
Text escapes widget boundaries

### ISSUE THREAD

**Issue by TheBizzle** [NetLogo/Galapagos#195]
Large amounts of text in widgets currently knows no boundaries, as you can see below:

![longwindedmonitor](https://cloud.githubusercontent.com/assets/912890/6171624/63207c34-b2a1-11e4-85bd-7f534e610dc1.png)

The very large list displayed in the `data` monitor here flows outside of the monitor, past the view, outside the boundaries of the model, and (as you can see from the scroll bar) right off the edge of the page.

The ideal behavior might be to make the contents of the widgets scrollable, but it would be sufficient for us to copy JVM NetLogo and just truncate any text that's too large.

**Comment by qiemem** [comment]
Scrollbars are pretty easy in themselves, but I'd be worried the scrollbars would hide contents on most systems without resize widgets (which we can't do).

Truncating is also quite easy.

**Comment by qiemem** [comment]
Or rather, we could resize, but it'd be a pain, and would be totally different behavior than NetLogo.
