### ISSUE TITLE
String input widgets should work

### ISSUE THREAD

**Issue by TheBizzle** [NetLogo/Galapagos#196]
Currently, string Input widgets are faulty.

[Here](https://gist.githubusercontent.com/TheBizzle/1134929b12788bc97d68/raw/4f59dbd3aab3057edab01839b3205069a758a09b/climate_derp.nlogo) is a version of Climate Change that uses a string Input (`derp`), where `derp` is a string to use as the shape for the sunrays in the model.  The default in this model is "person".  Inputting "ray" or "car" should affect the ray shape, but input text is discarded and has no effect.

**Comment by qiemem** [comment]
Looks like it's detecting the input type incorrectly (it's creating a number input instead of string). Should be an easy fix. I'll do it tonight.
