### ISSUE TITLE
Invalid monitor values should say "N/A"

### ISSUE THREAD

**Issue by TheBizzle** [NetLogo/Galapagos#210]
Instead, our monitors can say things like "NaN".  See the default state of the Fire model for an example of the bad behavior:

![nan](https://cloud.githubusercontent.com/assets/912890/6660488/78565544-cb68-11e4-9f06-3b15344e4d28.png)

**Comment by qiemem** [comment]
It currently just checks for errors: https://github.com/NetLogo/Galapagos/blob/a48724cc01f44e66a2fffdda411db580960e1c85/app/assets/javascripts/TortoiseJS/agent/widgets.coffee#L95

Is there anything besides `NaN` to add?
