### ISSUE TITLE
IE: Alignment and spacing of text is messed up

### ISSUE THREAD

**Issue by TheBizzle** [NetLogo/Galapagos#215]
Demonstration:

![badwsp](https://cloud.githubusercontent.com/assets/912890/6660572/88dbec74-cb6a-11e4-8127-3740a40ab64d.png)

"setup" seems to be placed correctly.  However, after "setup", "go" and the following checkboxes and monitors have their text and inner elements in the wrong places.

Occurs only in IE10.

**Comment by qiemem** [comment]
Almost all of this is done with flexbox, so this may just be a consequence of #216.

**Comment by qiemem** [comment]
I should note that `setup` is probably centered because that's the default position for button text. Forever buttons are actually checkboxes. I had this same problem on Safari before I added the `-webkit-` prefix.

**Comment by TheBizzle** [comment]
Fixed by 1d78a7d1a79f2996f42e28931d9000d49d469b3c
