### ISSUE TITLE
IE: Flexboxes are broken

### ISSUE THREAD

**Issue by TheBizzle** [NetLogo/Galapagos#216]
Demonstrations:

![badwsp](https://cloud.githubusercontent.com/assets/912890/6660572/88dbec74-cb6a-11e4-8127-3740a40ab64d.png)

![badwsp2](https://cloud.githubusercontent.com/assets/912890/6660622/6d168df4-cb6b-11e4-9e8b-cb472875e995.png)

![badwsp3](https://cloud.githubusercontent.com/assets/912890/6660624/6f87857a-cb6b-11e4-912a-5748655c59ff.png)

This causes all sorts of problems.  The "powered by NetLogo" thing is in the wrong spot.  The Speed Slider is too narrow and on its own line.  The Code and Info tabs' buttons are scrunched together.  If you open them both, their content stacks vertically (rather than splitting the space horizontally).  The "Find a Built-In Model or Upload a Model" inputs are aligned incorrectly.  The Command Center displays improperly when opened (which I'm just going to guess is flexbox related, but might not be).

I imagine that this also wreaks havoc on the other pages on the site.

Check out the `-ms-` prefix.

Occurs only in IE10.

**Comment by qiemem** [comment]
We should probably start using an auto prefixer or something to handle this kind of thing for us.

**Comment by mrerrormessage** [comment]
Just on the off-chance that someone working on this hasn't seen had an occasion to use an IE VM already, Microsoft makes them freely available (and for different versions, no less) [here](https://www.modern.ie/en-us/virtualization-tools). If you setup port-forwarding on the VM (assuming that's allowed in windows VMs) you can run the server in your native OS and browse from the VM.

**Comment by TheBizzle** [comment]
Fixed by 1d78a7d1a79f2996f42e28931d9000d49d469b3c
