### ISSUE TITLE
IE: Button text isn't horizontally centered

### ISSUE THREAD

**Issue by TheBizzle** [NetLogo/Galapagos#217]
Demonstration:

![badalignment](https://cloud.githubusercontent.com/assets/912890/6660680/5b1ed8c6-cb6c-11e4-9b55-a0bea07ed018.png)

Occurs only in IE 11.

**Comment by qiemem** [comment]
The centering is done with flexbox. [Can I use](http://caniuse.com/#search=flexbox) says IE11 fully supports flexbox, so not sure what's up.
