### ISSUE TITLE
"Disable until ticks start" should be supported in buttons

### ISSUE THREAD

**Issue by TheBizzle** [NetLogo/Galapagos#220]
This feature has a significant impact on the usability of models, so I think that we should make Tortoise-converted models respect this setting in the near future.

I'm not sure what the cleanest solution for this is, though.  Perhaps a button with this option enabled should be passing callbacks into the engine for when `reset-ticks` and `clear-ticks` are called (which will require some small engine changes and model initialization changes)?

**Comment by SethTisue** [comment]
I agree that this is high really priority (unfortunately, considering how much else there is to do). Until we added this feature, it was always the #1 usability problem with NetLogo models in the classroom. (And probably other settings too.)

**Comment by qiemem** [comment]
The [`tick`](https://github.com/NetLogo/Galapagos/blob/a48724cc01f44e66a2fffdda411db580960e1c85/app/assets/javascripts/TortoiseJS/agent/widgets.coffee#L21) attribute in the widgets data model already [updates automatically](https://github.com/NetLogo/Galapagos/blob/a48724cc01f44e66a2fffdda411db580960e1c85/app/assets/javascripts/TortoiseJS/agent/widgets.coffee#L115) (part of the normal polling that supports monitors, dynamic sliders, etc). We can bind whatever css classes/html properties are needed to `tick` or maybe add a `ticksStarted` that's backed by the same stuff.

**Comment by TheBizzle** [comment]
For clarity: Using `world.ticker.tickCount()` to do this won't cover all of the cases.  Grabbing the tick count after calling `clear-ticks` throws an error (`"The tick counter has not been started yet. Use RESET-TICKS."`).  Relatedly, the buttons should be disabled between invocations of `clear-ticks` and `reset-ticks`.

I think any solution that doesn't involve watching the update stream for `world.ticks === -1` will require an engine change (which isn't necessarily a bad thing).

**Comment by qiemem** [comment]
Doesn't checking to see if `world.ticker.tickCount()` throws that exception cover all cases?

`ticks` should actually blank out on exception. It's a bug that the `catch` is blank.

**Comment by TheBizzle** [comment]
It strikes me as a bad assumption to make that any error in calling `world.ticker.tickCount()` should be interpreted as "the value for `ticks` is currently invalid".  Even a simply typo will trigger that `catch` block.

**Comment by qiemem** [comment]
Alright, that's fine. Want to add `world.ticker.ticksStarted()` to the engine?

**Comment by TheBizzle** [comment]
Sure.  `world.ticker.ticksAreStarted()` has been implemented in [this commit](https://github.com/NetLogo/Tortoise/commit/9b775db86006859f38a16a8034959ae1f396ffb1).  Once Travis gives its stamp of approval, I'll merge it, publish an artifact, and let you know.

**Comment by TheBizzle** [comment]
Alright, current `master` is now pointing to an artifact where the engine has `world.ticker.ticksAreStarted()`.

**Comment by qiemem** [comment]
Alas, this is currently being serialized apparently. I'll try to get to this next week.

**Comment by qiemem** [comment]
That is, I meant to say, "Disable until ticks start" is currently not being serialized.

**Comment by qiemem** [comment]
This needs NetLogo/NetLogo-Headless#49
