### ISSUE TITLE
upgrade to Play 2.4

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/Galapagos#241]
Play 2.4 is out; see [migration guide](https://www.playframework.com/documentation/2.4.x/Migration24).

while there is no immediate need for us to upgrade, it's not good to fall too far behind, either

Java 8 is required, but that's fine for us, we're already there.

the big changes have to do with using dependency injection to reduce the reliance on global state. it looks like there is backwards compatibility stuff in place, so if we upgrade it could probably happen in two stages: first, just to get it running using compatibility stuff, second, move to the latest and greatest APIs. apparently some of the compatibility stuff emits deprecation warnings on the console, so let's watch for that.

**Comment by TheBizzle** [comment]
I have a fix for this on the `wip-play-24` branch, but I can't really merge it until @mrerrormessage and myself sort out these "duplicate mappings" issues that we're seeing now when we try to run the tests.  (The Autoprefixer is the suspect with regards to those woes.)
