### ISSUE TITLE
TortoiseJS should specify units for css width/height inside of style attributes

### ISSUE THREAD

**Issue by psndcsrv** [NetLogo/Galapagos#247]
Two examples of this (I'm not sure if there are others, but these were causing problems for me):
app/assets/javascripts/TortoiseJS/agent/widgets.coffee#L197
assets/javascripts/TortoiseJS/agent/widgets.coffee#L212

The width and height values supplied to Ractive are numeric, so they end up unit-less in the rendered html.

**Comment by TheBizzle** [comment]
I looked through the project, but the two lines you pointed out were the only ones that I found with missing units.

Thanks for the report!

**Comment by TheBizzle** [comment]
The fix for this is now up on the main Galapagos server.

**Comment by psndcsrv** [comment]
Thanks for fixing this so quickly! Getting such a quick response is always a pleasant surprise. It's very much appreciated!
