### ISSUE TITLE
'startup' procedures are no longer being called

### ISSUE THREAD

**Issue by psndcsrv** [NetLogo/Galapagos#249]
I'm guessing the moving of model-defined procedures out of the global namespace and into the `procedures` global broke this.

Perhaps changing app/assets/javascripts/TortoiseJS/control/session-lite.coffee#L21 to read:
`if procedures.startup? then Call(procedures.startup)`

**Comment by TheBizzle** [comment]
The fix for this can now be found on the main server.

**Comment by psndcsrv** [comment]
Perfect. Thanks!
