### ISSUE TITLE
"Tabs" not working correctly in Firefox

### ISSUE THREAD

**Issue by mrerrormessage** [NetLogo/Galapagos#251]
![screen shot 2015-06-25 at 8 22 00 am](https://cloud.githubusercontent.com/assets/143198/8355192/65656678-1b13-11e5-965e-aa5fd68ed550.png)

Tested using FF 38.0.5 for Mac OS X Yosemite.

**Comment by qiemem** [comment]
The problem doesn't show up in Chrome.

Can't tell what the problem is immediately. The code tab is behaving as though it's a fixed width. I'll see if I can figure it out.

**Comment by qiemem** [comment]
Adding `overflow: hidden` fixes the problem. It should probably have the `netlogo-widget` class anyway. Fix incoming.

**Comment by mrerrormessage** [comment]
Thanks for the quick fix!
