### ISSUE TITLE
Error running in an iframe in IE11

### ISSUE THREAD

**Issue by TheBizzle** [NetLogo/Galapagos#252]
_From @ToonTalk on June 26, 2015 8:2_

When I click on 'Play Game' after this loads: http://m.modelling4all.org/m/?EGM=1

It breaks on

  now = (_ref = typeof performance !== "undefined" && performance !== null ? performance.now.bind(performance) : void 0) != null ? _ref : Date.now.bind(Date);

where performance is defined but performance.now isn't. performance.timing is defined -- perhaps that is what IE calls it?

Works fine in Chrome and FireFox.

I tried to isolate this and discovered that without an iframe it works in IE11 and in some other circumstances it runs in an iframe OK

_Copied from original issue: NetLogo/Tortoise#156_

**Comment by qiemem** [comment]
I don't this is a problem on our end. [`perfomance.now()` is definitely support by IE11](https://msdn.microsoft.com/en-us/library/hh973355(v=vs.85).aspx). Furthermore, the [iframe works fine when embedded on a different page](http://jsfiddle.net/hq9rj6a4/4/).

**Comment by TheBizzle** [comment]
Indeed, there's something funny about the Modeling4All site with regards to `performance` on IE11.  On other sites, `performance.now` is present in my IE11.  Throughout the M4A site, it's missing.

In the M4A page source, I found this:

```
if(window.performance){var b=window.performance.timing,d=b.navigationStart,f=b.requestStart,a=a+(b[this.a+"EventStart"]-d),a=a+("&nav="+(b.fetchStart-d)),a=a+("&dns="+(b.domainLookupEnd-b.domainLookupStart)),a=a+("&connect="+(b.connectEnd-b.connectStart)),
```

Looks like something—GWT?—is messing around with the global `performance` object in some way...?  Nothing in that code appears to set `performance` or `performance.now`, but the whole thing looks pretty suspicious to me.

@ToonTalk, I would recommend some investigation on your end to find out what's tinkering with your `performance` object.

For now, closing this as "invalid".

**Comment by ToonTalk** [comment]
I tracked the problem down to the use of 

<meta http-equiv="X-UA-Compatible" content="IE=9">

removing it fixed the problem. I assume IE9 is not supported by Tortoise.

**Comment by ToonTalk** [comment]
Github stripped out the following

meta http-equiv="X-UA-Compatible" content="IE=9"

when surrounded by <>

**Comment by TheBizzle** [comment]
> I assume IE9 is not supported by Tortoise.

Correct.
