### ISSUE TITLE
Shape displayed incorrectly

### ISSUE THREAD

**Issue by TheBizzle** [NetLogo/Galapagos#258]
_From @ToonTalk on June 10, 2015 12:59_

Loading
to startup
  crt 1 [set shape "building institution" ; imported from the Shape Editor Library
         set color white
         set size 4]
end
produces the following in the JVM:
![image](https://cloud.githubusercontent.com/assets/2138696/8082889/a796ca92-0f78-11e5-8fa3-35261e3c16ca.png)

while the web version looks like this:
![image](https://cloud.githubusercontent.com/assets/2138696/8082923/dd4cdbd6-0f78-11e5-80f0-a9e273c6f232.png)

_Copied from original issue: NetLogo/Tortoise#149_

**Comment by TheBizzle** [comment]
I see nothing wrong here!

Just kidding....

[Here](https://gist.github.com/TheBizzle/8bc41a145398218c5432)'s a simple example model that makes it a bit clearer what it is that Tortoise is actually *doing*.

Here it is in JVM NetLogo:

![jvmbuildinst](https://cloud.githubusercontent.com/assets/912890/8091992/a6aca6e8-0f7c-11e5-9cd3-cbb9d660abba.png)

Here it is in Tortoise:

![tortoisebuildinst](https://cloud.githubusercontent.com/assets/912890/8092000/aaf22692-0f7c-11e5-9981-0a63c40b5b8e.png)

(Note that patches are colored randomly; just focus on the turtle shape.)

This is what's coming out of the shape serializer:

```
"building institution": {
  "rotate":   false,
  "elements": [
    {"xmin":0,"ymin":60,"xmax":300,"ymax":270,"type":"rectangle","color":"rgba(141, 141, 141, 1.0)","filled":true,"marked":true},
    {"xmin":130,"ymin":196,"xmax":168,"ymax":256,"type":"rectangle","color":"rgba(0, 0, 0, 1.0)","filled":true,"marked":false},
    {"xmin":0,"ymin":255,"xmax":300,"ymax":270,"type":"rectangle","color":"rgba(0, 0, 0, 1.0)","filled":false,"marked":false},
    {"xcors":[0,150,300],"ycors":[60,15,60],"type":"polygon","color":"rgba(141, 141, 141, 1.0)","filled":true,"marked":true},
    {"xcors":[0,150,300],"ycors":[60,15,60],"type":"polygon","color":"rgba(0, 0, 0, 1.0)","filled":false,"marked":false},
    {"x":135,"y":26,"diam":30,"type":"circle","color":"rgba(255, 255, 255, 1.0)","filled":true,"marked":false},
    {"x":135,"y":25,"diam":30,"type":"circle","color":"rgba(0, 0, 0, 1.0)","filled":false,"marked":false},
    {"xmin":0,"ymin":60,"xmax":300,"ymax":75,"type":"rectangle","color":"rgba(0, 0, 0, 1.0)","filled":false,"marked":false},
    {"xmin":218,"ymin":75,"xmax":255,"ymax":90,"type":"rectangle","color":"rgba(0, 0, 0, 1.0)","filled":false,"marked":false},
    {"xmin":218,"ymin":240,"xmax":255,"ymax":255,"type":"rectangle","color":"rgba(0, 0, 0, 1.0)","filled":false,"marked":false},
    {"xmin":224,"ymin":90,"xmax":249,"ymax":240,"type":"rectangle","color":"rgba(0, 0, 0, 1.0)","filled":false,"marked":false},
    {"xmin":45,"ymin":75,"xmax":82,"ymax":90,"type":"rectangle","color":"rgba(0, 0, 0, 1.0)","filled":false,"marked":false},
    {"xmin":45,"ymin":240,"xmax":82,"ymax":255,"type":"rectangle","color":"rgba(0, 0, 0, 1.0)","filled":false,"marked":false},
    {"xmin":51,"ymin":90,"xmax":76,"ymax":240,"type":"rectangle","color":"rgba(0, 0, 0, 1.0)","filled":false,"marked":false},
    {"xmin":90,"ymin":240,"xmax":127,"ymax":255,"type":"rectangle","color":"rgba(0, 0, 0, 1.0)","filled":false,"marked":false},
    {"xmin":90,"ymin":75,"xmax":127,"ymax":90,"type":"rectangle","color":"rgba(0, 0, 0, 1.0)","filled":false,"marked":false},
    {"xmin":96,"ymin":90,"xmax":121,"ymax":240,"type":"rectangle","color":"rgba(0, 0, 0, 1.0)","filled":false,"marked":false},
    {"xmin":179,"ymin":90,"xmax":204,"ymax":240,"type":"rectangle","color":"rgba(0, 0, 0, 1.0)","filled":false,"marked":false},
    {"xmin":173,"ymin":75,"xmax":210,"ymax":90,"type":"rectangle","color":"rgba(0, 0, 0, 1.0)","filled":false,"marked":false},
    {"xmin":173,"ymin":240,"xmax":210,"ymax":255,"type":"rectangle","color":"rgba(0, 0, 0, 1.0)","filled":false,"marked":false},
    {"xmin":269,"ymin":90,"xmax":294,"ymax":240,"type":"rectangle","color":"rgba(0, 0, 0, 1.0)","filled":false,"marked":false},
    {"xmin":263,"ymin":75,"xmax":300,"ymax":90,"type":"rectangle","color":"rgba(0, 0, 0, 1.0)","filled":false,"marked":false},
    {"xmin":263,"ymin":240,"xmax":300,"ymax":255,"type":"rectangle","color":"rgba(0, 0, 0, 1.0)","filled":false,"marked":false},
    {"xmin":0,"ymin":240,"xmax":37,"ymax":255,"type":"rectangle","color":"rgba(0, 0, 0, 1.0)","filled":false,"marked":false},
    {"xmin":6,"ymin":90,"xmax":31,"ymax":240,"type":"rectangle","color":"rgba(0, 0, 0, 1.0)","filled":false,"marked":false},
    {"xmin":0,"ymin":75,"xmax":37,"ymax":90,"type":"rectangle","color":"rgba(0, 0, 0, 1.0)","filled":false,"marked":false},
    {"x1":112,"y1":260,"x2":184,"y2":260,"type":"line","color":"rgba(0, 0, 0, 1.0)","filled":false,"marked":false},
    {"x1":105,"y1":265,"x2":196,"y2":265,"type":"line","color":"rgba(0, 0, 0, 1.0)","filled":false,"marked":false}]
}
```

This seems correct to me.  My guess as to what's going wrong is that Beak (over in Galapagos) is drawing the black rectangles as filled, even when they're not supposed to be.

Assigning to @mrerrormessage for further investigation.

**Comment by TheBizzle** [comment]
Pinging @mrerrormessage

**Comment by TheBizzle** [comment]
_From @mrerrormessage on July 6, 2015 21:37_

I was hoping to wrap up [Galapagos 237](https://github.com/NetLogo/Galapagos/issues/237) first, and then circle back on this one. I've spent a few minutes investigating and have some ideas for when I start on this one. Let me know if this is higher priority than Galapagos#237, and I'll switch over right away.

**Comment by TheBizzle** [comment]
_From @mrerrormessage on July 8, 2015 14:49_

Given my unfamiliarity with the Galapagos rendering code, I'm not sure yet what the appropriate fix is, but I do know the *cause* of the problem is a `lineWidth` value that has been set way higher than needed. By changing [this line](https://github.com/NetLogo/Galapagos/blob/master/app/assets/javascripts/TortoiseJS/agent/drawshape.coffee#L19) to `ctx.lineWidth = 3` (the current value divided by 10, arbitrarily chosen), I got the following:
![screen shot 2015-07-08 at 9 41 17 am](https://cloud.githubusercontent.com/assets/143198/8573279/6ee3e254-2556-11e5-99c1-c8c184cea195.png)
Before checking in that change, I want to understand a bit more about why the `lineWidth` was set as it was, since I'm assuming there was a good reason behind it, and I would prefer not to use arbitrary numbers just because they make some shapes "look right". Line width was last changed in [this fix](https://github.com/NetLogo/Galapagos/issues/164) by @qiemem , perhaps he could offer some insight into this issue and why the value was reset from 15 to 30?

**Comment by TheBizzle** [comment]
_From @qiemem on July 8, 2015 17:16_

That original commit was due to the opposite problem. The lines in some shapes were so thin that they could barely be seen (they looked like a dashed set of pixels). I believe 15 -> 30 was determined empirically.

I *think* that the `.1` in [this line](https://github.com/NetLogo/Galapagos/blob/97c6fa0f4e383bc9c6727f7563db4a3e332d40fd/app/assets/javascripts/TortoiseJS/agent/drawshape.coffee#L2) should actually be the same as [`onePixel` in view.coffee](https://github.com/NetLogo/Galapagos/blob/97c6fa0f4e383bc9c6727f7563db4a3e332d40fd/app/assets/javascripts/TortoiseJS/agent/view.coffee#L80). That's mostly a guess though.

Even if that guess is right, it will only push back the problem. Line width in desktop NetLogo is independent of turtle size. At `size = 1`, that building shape looks like: 

![image](https://cloud.githubusercontent.com/assets/28215/8576597/b95a2958-2568-11e5-9839-615ca8d176b9.png)

NetLogo Web looks pretty much identical at that size (so much so that I think this is probably the comparison I optimized against):

![image](https://cloud.githubusercontent.com/assets/28215/8576669/543a798c-2569-11e5-9f12-bbf9fe7b2dd5.png)


Compare this with desktop NetLogo at `size = 30`:

![image](https://cloud.githubusercontent.com/assets/28215/8576624/01b2ca66-2569-11e5-9246-81b7e38f6f6d.png)

The width of lines is the same even though the rest of the image has scaled.

In NetLogo Web, each shape/color combination is cached on a 300x300 canvas that is simply scaled and stamped when displayed on the view. Thus, line widths scale with the rest of the image. So even if we fix this problem by lowering the line width, at some scales, lines that should be visible won't be.

The real solution is to cache different image sizes. I didn't do this originally because of memory fears  and I wasn't certain it would be necessary. We'd actually see a memory savings for models that don't change sizes of turtles, since the average size of the cached images will be smaller (300x300 is really big). But we would likely have to build a real LRU or LFU cache. Perhaps we'd want to cache regular intervals of image sizes (e.g. `size = 1` and `size = 1.2` would use the same cached image). Any solution should also take into account screen DPI  (the [view's `quality` attribute already does this for the view canvas](https://github.com/NetLogo/Galapagos/blob/97c6fa0f4e383bc9c6727f7563db4a3e332d40fd/app/assets/javascripts/TortoiseJS/agent/view.coffee#L72) itself, but the cached images would also need to) .

**Comment by TheBizzle** [comment]
I'm not sure the necessity of the shape cache has been established.  I'd like to see the line thickness behavior fixed for NLW 1.0 for sure.  Implementing a shape cache that accounts for shape sizes can be a secondary goal.

**Comment by qiemem** [comment]
Setting `LINE_WIDTH` to 15 instead of 30:

![image](https://cloud.githubusercontent.com/assets/28215/8577459/6b5cf9b4-256e-11e5-90ec-f4326426f60c.png)


In Mimicry:

![image](https://cloud.githubusercontent.com/assets/28215/8577469/80218982-256e-11e5-81ef-e753cb871b4b.png)

So both suck :-(

This is on my lower DPI external monitor BTW (`devicePixelRatio = 1.0`). On my retina, Mimicry looks a bit better, but not fantastic.

**Comment by TheBizzle** [comment]
@skorlir and I have long since noticed problems with the `quality` calculation.  We found that lowering that number led to shapes that looked better on our machines.  Perhaps some investigation into that calculation is in order.

**Comment by qiemem** [comment]
Lowering? `quality = 1` in those images. Setting it to `0.5` looks like this:

![image](https://cloud.githubusercontent.com/assets/28215/8577644/bdff1e12-256f-11e5-9f16-0b2410321cd3.png)

(again, on my external monitor).

*Raising* looks a touch better, but still unacceptably bad:

![image](https://cloud.githubusercontent.com/assets/28215/8577668/ddb4d47c-256f-11e5-8dac-32dde0012c04.png)

(these are both `LINE_WIDTH = 15`)

**Comment by TheBizzle** [comment]
(Note: Solving this will almost certainly address #221)

**Comment by qiemem** [comment]
Some more comparison shots:

`LINE_WIDTH = 30`, `quality = 1`:

![image](https://cloud.githubusercontent.com/assets/28215/8577734/4e9380da-2570-11e5-96ca-5c4719061384.png)

`LINE_WIDTH = 30`, `quality = 2`:

![image](https://cloud.githubusercontent.com/assets/28215/8577742/5e91c0e6-2570-11e5-85df-e2199abdf4d3.png)

`LINE_WIDTH = 30`, `quality = 0.5` looks pretty much the same as the `LINE_WIDTH = 15`, `quality = 0.5` in my previous comment.

**Comment by qiemem** [comment]
> (Note: Solving this will almost certainly address #221)

You mean caching different sized images would solve #221, correct? Simply changing line width will not. If we made lines small enough for Koch Curve to look right, lines in the vast majority of cases would be invisible.

**Comment by SethTisue** [comment]
(iirc, in JVM NetLogo line segments in turtle shapes are always rendered as hairlines, regardless of the patch size, turtle size, etc)

**Comment by TheBizzle** [comment]
> You mean caching different sized images would solve #221, correct?

I mean that any thing that solves the real problem here (which is that we should not be drawing shapes at a fixed size and then scaling them) should solve #221.

**Comment by ToonTalk** [comment]
I don't know the full context but when I read "Perhaps we'd want to cache regular intervals of image sizes (e.g. size = 1 and size = 1.2 would use the same cached image)" I wondered why pre-cache anything? When an image and size is needed look in the cache for it and otherwise compute it, cache it, and use it.

**Comment by qiemem** [comment]
> I don't know the full context but when I read "Perhaps we'd want to cache regular intervals of image sizes (e.g. size = 1 and size = 1.2 would use the same cached image)" I wondered why pre-cache anything?  

Ah, sorry, I didn't mean to imply that we would be *pre*-caching anything. We would cache on demand as you say, but round the cached image sizes to reduce the number of cache entries. We're already doing this with RGB colors (rounding to integers).

I might be over-worried about the memory hit of caching multiple sizes. The worst cases for the cache are things like turtles growing in small increments and, for instance, turtle size indicating some network measurement in a network (especially if color is being used to indicate something else). Rounding might be enough that we don't have to worry about memory.

Anyway, I'm first going to solve this bug without caching at all, see what it's like, and add the cache back in as needed.

**Comment by ToonTalk** [comment]
Makes sense. If you do end up needing to cache, then the rounding could depend upon patch-size such that sub-pixel size changes are rounded away. But patch-size is the number of pixels across a patch only if the browser window is scaled to 100%.

**Comment by qiemem** [comment]
A discussion arose on gitter regarding clipping and NetLogo/NetLogo#823 came out of it. Basically, clipping in NetLogo is pretty much an accident. That said, most of us seemed to agree that clipping to a 300x300 square made sense. Mimicry is a good example of why. Clipping also makes caching significantly easier. So, I think we should keep the clipping in NLW and will work off that for now.

**Comment by qiemem** [comment]
I should've posted the model I used to test the cache: https://gist.github.com/qiemem/08b515740c591bd7df01
