### ISSUE TITLE
Add Export to HTML Button to /tortoise

### ISSUE THREAD

**Issue by mrerrormessage** [NetLogo/Galapagos#266]

**Comment by TheBizzle** [comment]
Destroy `/create-standalone`.  Concatenate all the JS and the `.nlogo` text.  On load, compile the `.nlogo` and load up the model.  @qiemem suggests using a library to read each script and stylesheet asynchronously.  Can get rid of header stuff in standalone pages, but link back to the proper NetLogo Web page.

**Comment by qiemem** [comment]
Does this need to happen client-side or can we just adapt our current standalone generator? It would simplify things to do it server-side, and we wouldn't lose the compiler.

**Comment by TheBizzle** [comment]
It needs to be client side.  There is no server-side web app anymore.

**Comment by qiemem** [comment]
Ah, ok. Didn't realize we'd actually decided on getting rid of it completely.

**Comment by qiemem** [comment]
Paraphrasing an in-person discussion: We've decided to generate the basic wrapper (with all inlined JS and such) at build-time via a Play template. The browser will then insert the nlogo code into this wrapper.
