### ISSUE TITLE
Streamline NetLogo Web site design

### ISSUE THREAD

**Issue by mrerrormessage** [NetLogo/Galapagos#267]
landing:

* Link to JVM NetLogo
* Link to NetLogo Web in-browser page

**Comment by mrerrormessage** [comment]
This is what I currently have. Would appreciate feedback, especially from @qiemem and @TheBizzle:
![screen shot 2015-07-21 at 9 58 20 am](https://cloud.githubusercontent.com/assets/143198/8803947/5783c88e-2f8f-11e5-886e-289e618f18ac.png)

**Comment by qiemem** [comment]
I like it, but why isn't Chrome listed with the browsers?

**Comment by mrerrormessage** [comment]
I had that initially, but it seemed confusing to have Chrome in there twice, since I wanted to single out that it works on Chromebooks. I wanted to keep the number of items the same in both lists as that makes things line up a bit better. Perhaps listing Chrome with the browsers and singling out the iPad as the second supported device?

**Comment by qiemem** [comment]
I think sticking Chrome with the browsers and leaving mobile devices as is would be fine. Working on the Chrome browsers implies that it works on Chrome OS. Having a single symbol to cover iPhone and iPads seems fine to me.

Is that really the icon for iPhones/iPads?

**Comment by mrerrormessage** [comment]
The official iphone logos seem to be either an apple with the word "iPhone" next to it, or the above image with the word "iphone" next to it. Either that or I'm bad at google images searches. At any rate, I wanted a roughly square logo so that it would match the other logos.

**Comment by TheBizzle** [comment]
(FYI, "NetLogo Desktop" should be known simply as "NetLogo".)

I pondered this a bit, and I think it's best if we don't do any of this browser/OS icon stuff.  The problem is that it's not as simple as "If you're on Windows, use NetLogo; if you're using Chrome, go with NetLogo Web".  The two aren't mutually exclusive, and the "NetLogo doesn't work on my platform" problem only covers a minority of the intended use cases for NetLogo Web.

Instead, I think it would be preferable to remove the browser/OS icons and just have some text underneath the buttons that says, "Not sure which one is right for you?  See the [FAQ](http://mymadeuplinkthatdoesnot.go/anywhere/right/now) to learn more!"

**Comment by mrerrormessage** [comment]
![screen shot 2015-07-21 at 11 33 32 am](https://cloud.githubusercontent.com/assets/143198/8806456/602ffc7a-2f9c-11e5-9573-e18526ef1a0e.png)
Here is a screenshot of the page with your changes. If I wasn't already familiar with NetLogo and NetLogo Web, I think I would find this page a bit confusing. Imagining that I am a user (especially a new user), I would prefer to see the FAQ information about which version is right for me on the same page than to have to navigate to another page and then navigate back to choose. Choosing between the two is definitely more complex that simply identifying the target platform; I think it would be good to see if we could find a way to bring those out on the landing page.

**Comment by qiemem** [comment]
> I would prefer to see the FAQ information about which version is right for me on the same page than to have to navigate to another page and then navigate back to choose.

This seems like a good idea. First question should be "What is this?". Second or third should be "Which one is right for me?"

**Comment by TheBizzle** [comment]
![602ffc7a-2f9c-11e5-9573-e18526ef1a0e](https://cloud.githubusercontent.com/assets/912890/8807276/f7d9906e-2fa0-11e5-91be-52e55aa94031.png)

Except with a bigger font size

**Comment by SethTisue** [comment]
maybe something like this would help someone make a snap decision?

NetLogo: desktop app. requires download. works offline. complete feature set. high performance.
NetLogo Web: web-based. no download. works on mobile devices. basic feature set.

**Comment by mrerrormessage** [comment]
Per @SethTisue . This is my favorite so far.
![screen shot 2015-07-21 at 12 28 29 pm](https://cloud.githubusercontent.com/assets/143198/8807734/0d3d95f6-2fa4-11e5-85d2-df7759aebc08.png)
I would like to see a little bit more decoration around the text - maybe big green check marks next to them or something? But whether that's there or not, I really like it.

**Comment by qiemem** [comment]
Ooh, that's really nice.

**Comment by UriCCL** [comment]
For now, I think we should make netlogo more prominent and netlogo web as an alternative.
And the acknowledgement text currently only refers to netlogo web. Most of those acknowledgements are really for netlogo.
Netlogo web gets one main acknowledgement, the inquiry space project.

—Uri

Uri Wilensky

**Comment by TheBizzle** [comment]
InquirySpace is mentioned as the NetLogo Web funding source after the beginning of that blurb.  My reasoning for providing the other acknowledgements was that NetLogo Web reuses a very large percentage of the JVM NetLogo compiler, which was funded by (at least some of) those other grants.

**Comment by UriCCL** [comment]
I understand your reasoning. But for NSF, they’d want only Iqspace credit for netLogo web.
It would be fine to have language like:

NetLogo Web builds on many years of funding for NetLogo…. then list funding for NetLogo.


—Uri

Uri Wilensky

**Comment by Idloj** [comment]
Why is the turtle's background on NetLogo Web is a gradient rather than sharp edges like the familiar NetLogo icon?
Why is the turtle smaller?

**Comment by SethTisue** [comment]
we do have the original Photoshop document for the icon in version control, so it should be possible to use the "real" turtle: https://github.com/NetLogo/NetLogo/blob/5.x/dist/icon.psd

**Comment by Idloj** [comment]
and, yeah, generally it should be more similar to the original icon

**Comment by Idloj** [comment]
also note that NLW icon doesn't have the drop shadow effect that the original icon has

**Comment by mrerrormessage** [comment]
That PSD shows the turtle with a black background when I open it in GIMP
![screen shot 2015-07-22 at 9 48 00 am](https://cloud.githubusercontent.com/assets/143198/8828236/c0af818c-3056-11e5-868b-42ce886ed050.png), but the turtle shape could be used.
I'm not a graphic designer and I spent like an hour or two on this, so I don't expect that it will be amazing. If someone else wants to take a stab at it, they're welcome to do so, I'll even send my GIMP file over. I liked the gradient as opposed to sharp edges*. I also liked that it looked visually distinct from the original logo, while still maintaining similarity*. I think it would be difficult to get the cloud shape to be recognizable and have the turtle be the same size as the original*. I'm not positive that a cloud is the best choice to represent the idea of "Web"*, but we already had a cloud shape in the library already, and that shape is the one used in the image.

**Comment by Idloj** [comment]
1) Which library?
2) I do think that the background difference is sufficient to distinct between the icons and everything else should be the same.
3) Until you mentioned it, I had no idea that the cloud is for web. I thought it's just night because the original icon is day.

*I'm not a graphic designer too, but I read/watched some material in the subject

**Comment by TheBizzle** [comment]
Rather than talking about the changes in the abstract, I think that we'd need to see alternative icons before we could really vote on them.  The current icon that @mrerrormessage put forth is not something that we're really set upon, and I don't expect that it will be the permanent icon for NetLogo Web.  Alternatives are welcome, but not of immediate importance.

**Comment by Idloj** [comment]
I have extracted the turtle for use:
![netlogo-turtle](https://cloud.githubusercontent.com/assets/8083458/8834252/cdcd1cc0-30bb-11e5-99d3-12301793ffa6.png)

**Comment by Idloj** [comment]
Does NLW even needs to have a different icon?
I can't come up with any software that uses a different icon for their web app and desktop app(the fact that I don't doesn't mean there isn't)

**Comment by TheBizzle** [comment]
That's a valuable question.  I think the intention of the page is clearest with some icons (like we have), but they need not be NetLogo-specific icons.  I could see an argument for how they could instead just be (for example) a cloud and a desktop computer.

**Comment by Idloj** [comment]
The one for NLW could just be the standard icon with a "web" stamp on it(on the corner)

**Comment by Idloj** [comment]
This is kind of my idea (just ad-hoc, I didn't made it the right way, just a fast "see how it looks"):
![snapshot19](https://cloud.githubusercontent.com/assets/8083458/8837065/27afa95e-30cd-11e5-9428-c4fadca137bd.png)
The stamp's color is TBD of course.

**Comment by TheBizzle** [comment]
I would prefer if the two images looked very immediately distinct from one another.

**Comment by qiemem** [comment]
> I would prefer if the two images looked very immediately distinct from one another.

Agree completely.

**Comment by Idloj** [comment]
I think the core problem(that's how I see it) is that we consider NetLogo and NetLogo-Web distinct products, but they shouldn't be. If you have a web app and a desktop app they are the very same product, just a desktop version and a web version. They are the same single product.

**Comment by TheBizzle** [comment]
I feel that I could make a strong argument that they're *not* both the same product.  Regardless of the outcome of that argument, choosing between the two has pretty massive consequences on the user's experience and possible uses.  This distinct choice should be visually represented with two very distinct images.

**Comment by SethTisue** [comment]
I agree with @TheBizzle, the gulf between the capabilities of the two versions is currently vast and is likely to remain so for a long while yet to come.

**Comment by Idloj** [comment]
what do you mean
> and is likely to remain so for a long while yet to come.
I thought NLW is meant to be in par with Netlogo in a future version, it is intended to be an applet replacement

**Comment by SethTisue** [comment]
at the moment we are designing icons and web pages for now, not for a future that will take a long time to arrive. (it has taken us years even just to get NLW to where it is now.)

**Comment by Idloj** [comment]
the problem with icons is that once users are familiar with NLW as a distinct product, it would be hard to impossible to unite the two, so you can't really design icons for now.(at least if you know the goal of having NLW in par with Netlogo, and you know)

**Comment by TheBizzle** [comment]
Okay, then let's not design icons right now.

**Comment by Idloj** [comment]
I give up

**Comment by frankduncan** [comment]
I actually agree with Idloj here.  Brand is about communication, and logo is about Brand.  By communicating that NetLogo and NetLogo Web are two distinct products (and to be fair, they are significantly closer at this point than NetLogo and NetLogo Applets in many technical respects), we aren't just communicating what is, but also what we believe should be.  We're presenting a choice when they come to the CCL for NetLogo.  Doing ABM research?  Here's a choice.  A PHD working at the CCL who wants to spend tens of hours on a grant?  Choice.  Hundreds of hours writing a dissertation on ABM and you want to use NetLogo?  Choice.

As such, I'm surprised that the Brand Manager for the CCL and NetLogo Web went along with this.  It will only serve to continue to split resources, not just within the CCL, but in the greater NetLogo community.  And this logo is probably quite important.  It will probably appear in papers, in articles, on webpages, and so on, more so than probably any other artifact of NetLogo Web in existence today.  I can't imagine anyone who wants NetLogo Web to be the future of NetLogo would go along with acknowledging they were competing, distinct products that anyone has a choice between

About the only people who I think would be happy to see such a split would be people interested in a long life for JVM NetLogo.  I guess I should say thanks then?
