### ISSUE TITLE
Misc. cleanup of '/tortoise' page

### ISSUE THREAD

**Issue by TheBizzle** [NetLogo/Galapagos#283]
We talked a bit about a variety of small, stylistic tweaks for the '/tortoise' page.  Here's what we came up with:

  * ~~Flex/horizontally center main content area~~ (a766d5c6d5df33d5b1f9788e9fc887ac842c39b6)
  * ~~Use same (sans serif) font uniformly~~ (a766d5c6d5df33d5b1f9788e9fc887ac842c39b6)
  * ~~Style the page to look like the other pages on the site~~ (eb173940de630ad419e160e0715b7822062f23da)
  * ~~Remove Bootstrap?~~ (fdb5dd0d06a3db4b9e276658e97dd8ff9eed8035)
  * ~~Change URL (can't be "tortoise" anymore)~~ (f5fb0bdcfb38636084d750eb372608303ca4caa7)
  * ~~Maybe change the default colors of the widgets, since none of us like them?~~ (df4d70b32e5606b9bf16fad9236aa9d5cf44c3d5)
  * ~~Keep tab buttons where they are, but maybe change how they look~~ (90870c444f2a3ee8a09831dc59fe93e8654d62d2)
  * ~~Redo the model selection interface at the top of the page~~ (eb173940de630ad419e160e0715b7822062f23da)

I'm open to discussing these things, adding more, or breaking some off into separate issues.  This issue isn't assigned to any particular person, and people should feel free to personally handle as much or as little of this issue as they would like.

**Comment by Idloj** [comment]
I suggest putting the command center on the bottom and two sections - one on the left and one on the bottom - that can be opened/closed (default opening state is tbd).
(When they are closed, they look like a bar on the side.)
(This is blocked, of course, by "horizontally center main content area".)

**Comment by mrerrormessage** [comment]
> Style the page to look like the other pages on the site
This is now available for review https://github.com/NetLogo/Galapagos/pull/291

**Comment by TheBizzle** [comment]
These are all done.  And thus is the 1.0 milestone closed out.

:tada: :cake: :tada:

**Comment by nicolaspayette** [comment]
You guys rock!
