### ISSUE TITLE
security is, ahem, an issue

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/Galapagos#3]
I shouldn't be able to do stuff like `file-open "/etc/passwd" repeat 100 [ print file-read-line ]` and so forth.

maybe install a SecurityManager?

**Comment by Idloj** [comment]
You can do it from a shell

**Comment by SethTisue** [comment]
this is a Teletortoise issue, not Tortoise

**Comment by TheBizzle** [comment]
This issue was moved to NetLogo/Teletortoise#12
