### ISSUE TITLE
Weird error messages when having several lines with missing closing quotation marks

### ISSUE THREAD

**Issue by arthurhjorth** [NetLogo/Galapagos#307]
edit: whoops, forgot to describe what caused this in the issue title. Fixed.

I was playing around with the Climate Change model in NLW yesterday, trying to break it, and ran into this weird... bug? Something. The result is that the error messages you get seem sort of random. I was playing around with the `setup` procedure, which looks like this:

```
to setup
  clear-all
  set-default-shape rays "ray"
  set-default-shape IRs "ray"
  set-default-shape clouds "cloud"
  set-default-shape heats "dot"
  set-default-shape CO2s "CO2-molecule"
  setup-world
  set temperature 12
  reset-ticks
end
```

If I remove the `"` in line 5 after cloud,  

```
to setup
  clear-all
  set-default-shape rays "ray"
  set-default-shape IRs "ray"
  set-default-shape clouds "cloud ;; removed closing quotation mark
  set-default-shape heats "dot"
  set-default-shape CO2s "CO2-molecule"
  setup-world
  set temperature 12
  reset-ticks
end
```
I get error message "Closing double quote is missing". So far so good.  I then removed the quotation mark in line 6 after dot, but accidentally removed the t too:

```
to setup
  clear-all
  set-default-shape rays "ray"
  set-default-shape IRs "ray"
  set-default-shape clouds "cloud ;; removed closing quotation mark
  set-default-shape heats "do ;; 't"' gone
  set-default-shape CO2s "CO2-molecule"
  setup-world
  set temperature 12
  reset-ticks
end
```
and then I get "Nothing named DO has been defined".

I tried to move the missing quotation mark up a line like this:
```
to setup
  clear-all
  set-default-shape rays "ray"
  set-default-shape IRs "ray
  set-default-shape clouds "cloud"
  set-default-shape heats "do
  set-default-shape CO2s "CO2-molecule"
  setup-world
  set temperature 12
  reset-ticks
end
```
but I get the same "Nothing named DO has been defined"-message.

In desktop NetLogo, if I do the exact same things, I correctly get the "Closing double quote is missing"-message.

**Comment by SethTisue** [comment]
@mrerrormessage looks like a bug in your reimplementation of the lexer?

related: I see TokenizerTests got copy-and-pasted between the JVM and JS code, is that duplication you were thinking of eventually eliminating?

**Comment by mrerrormessage** [comment]
@SethTisue , this is a bug in the reimplementation of Tokenizer. I'll look at fixing it.

There is also a lot of duplication between the tests; I was basically copying and pasting at the time I wrote them. I have since developed some more sophisticated strategies for managing tests that should be run both in JVM and JS that I can employ to reduce duplication.

**Comment by TheBizzle** [comment]
This issue was moved to NetLogo/NetLogo-Headless#59
