### ISSUE TITLE
Multi-line text input boxes are single line

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/Galapagos#313]
I made a string multi-line input box and got

![image](https://cloud.githubusercontent.com/assets/2138696/9327969/7ce314fe-459c-11e5-8740-652d4074e0ad.png)

with no way to enter multi-lines (other than \n)

Chrome Version 44.0.2403.155 m (Windows 7)

**Comment by TheBizzle** [comment]
Related is my comment in #269:

> Multiline Inputs should support editing the text in a larger editor

**Comment by TheBizzle** [comment]
Fixed by bfc0dec
