### ISSUE TITLE
Support directed links and link shapes

### ISSUE THREAD

**Issue by qiemem** [NetLogo/Galapagos#32]
Link shapes determine how directed links are shown, thus I have combined these two features into one issue.

It might be best to do this in stages:
1) Support direction indicator
2) Support curviness
3) Support multi-line links

**Comment by skorlir** [comment]
Link shapes is currently a non-starter because the linkShapesList passed to workspace is currently always just empty objects.

**Comment by TheBizzle** [comment]
Here is the format in which links are serialized:

```
Link: {
  "direction-indicator": <turtle shape>,
  "curviness":           <number>,
  "lines":               <array of lines>
}

Line: {
  "x-offset":   <number>,
  "is-visible": <boolean>,
  "dashes":     <array of numbers>
}
```
