### ISSUE TITLE
Google Drive no longer a hosting option

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/Galapagos#320]
http://netlogoweb.org/info states

Like any other HTML file, files generated in this way can then be hosted on a web server (including on Google Drive or Dropbox)

According to

http://googleappsdeveloper.blogspot.co.uk/2015/08/deprecating-web-hosting-support-in.html

the Google Drive support has been deprecated. Sad.

**Comment by TheBizzle** [comment]
That *is* pretty unfortunate.  Thanks for letting us know.  I've updated the FAQ accordingly.
