### ISSUE TITLE
Widgets are only updating when there are View updates

### ISSUE THREAD

**Issue by TheBizzle** [NetLogo/Galapagos#321]
A simple way to reproduce: Open Climate Change, and type in the Command Center `set temperature 20`.  Notice how the monitor doesn't update.  Then type `tick` and see that it does update.

Introduced in d2bccf518964004a174955c670eb3a2b598e1c12
Reported by Michal Kvasnička on the ccl-bugs mailing list

**Comment by qiemem** [comment]
This was almost certainly caused by this commit/line: https://github.com/NetLogo/Galapagos/commit/d2bccf518964004a174955c670eb3a2b598e1c12#diff-251f4ffc3b913e65da2fd7a604fdab9dR65

I think it just needs to be moved back an indent level.

**Comment by qiemem** [comment]
Bah, beat me to it.
