### ISSUE TITLE
Incompatible with Screen Readers

### ISSUE THREAD

**Issue by daqu3650** [NetLogo/Galapagos#324]
I noticed that NLW seems to stall or crash with various screen readers.

I discovered this bug because a student apparently turned on Chrome Vox (http://www.chromevox.com/) on a Chromebook. When you use Chrome Vox and open a simulation (e.g. http://inquiryhub.dls.ucar.edu/bio/BacteriaGrowthComplex.html or http://inquiryhub.dls.ucar.edu/bio/InvasiveSpeciesMidwest.html), the simulation stops working. Interestingly, Simulation 1 reports an error (text at bottom). Simulation 2 does not report any error.

WebAnywhere (http://webanywhere.cs.washington.edu/wa.php) also demonstrates similar problems.

Error
It looks like you're using NetLogo Web in standalone mode. 
If the above error is being caused by an unimplemented primitive, we recommend a quick visit to NetLogoWeb.org to see if the primitive has been implemented in the most up-to-date version.

**Comment by TheBizzle** [comment]
I can't seem to get the screen readers to work with other rich HTML5 applications, either, so it seems to me like this is a bug in—limitation of?—the screen readers.  Thanks for the report, but closing as "won't fix".
