### ISSUE TITLE
Command/reporter string Inputs should be syntax highlighted

### ISSUE THREAD

**Issue by TheBizzle** [NetLogo/Galapagos#334]
Syntax highlighting already exists via CodeMirror in Code tab; it just has to be triggered in the Ractive template for Input widgets when they're command or reporter Inputs.

This ticket has lineage of procrastination a la #269.

**Comment by LaCuneta** [comment]
Looks like this feature was added with [this commit](https://github.com/NetLogo/Galapagos/commit/b22a8cdcd1d1d8f4c7e0b9b3709fe04a09803444).
