### ISSUE TITLE
View shrinks to tiny size

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/Galapagos#335]
When I run this

http://www.netlogoweb.org/web?http://m4a-gae-hrd.appspot.com/p/Lye6ouseEv4UIXfFdxYg5_.nlogo

I see the view shrink to a tiny size:

![image](https://cloud.githubusercontent.com/assets/2138696/13915551/6f3f8c62-ef90-11e5-84f9-0776111c7f5e.png)

However if I then export the HTML all seems fine (view has patch size of 5).

**Comment by TheBizzle** [comment]
Hmm, strange.

I tried this on Opera, Chrome, Firefox, and Edge (all on Windows 10), and I cannot reproduce the behavior in the screenshot.  The fact that it works fine when you export suggests to me that this might be a caching issue of some sort.  Could you try clearing your browser cache and hitting the link again?

If the problem persists, could you tell us more about your setup (e.g. operating system and version, browser and version)?

**Comment by ToonTalk** [comment]
Problem went away today without explicitly flushing the cache. Yesterday I was able to reproduce the problem several times.

But I noticed a new problem with this model only on IE11. See #336
