### ISSUE TITLE
sort of RGB colors causes "We don't know how to sort your kind here!"

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/Galapagos#337]
observer> show sort [color] of turtles
observer: [5 45 45 45 105 105]

The following triggers an error with the message "We don't know how to sort your kind here!"

observer> show sort [pcolor] of n-of 6 patches

This was very confusing until I saw that the patch colors were RGB. [[77 188 253] [77 188 253] [255 255 255] [77 188 253] [229 77 253] [229 77 253]]

The desktop version returns [] with no error (which is odd but [documented](http://ccl.northwestern.edu/netlogo/docs/dictionary.html#sort)):

> sort list
> sort agentset
> Reports a sorted list of numbers, strings, or agents.
> 
> If the input contains no numbers, strings, or agents, the result is the empty list.

**Comment by TheBizzle** [comment]
This issue was moved to NetLogo/Tortoise#180
