### ISSUE TITLE
Sometimes hardware acceleration causes canvas problems in IE11

### ISSUE THREAD

**Issue by TheBizzle** [NetLogo/Galapagos#338]
A couple of times now, issues have come in up this repo where things in the View/canvas don't display properly under particular circumstances that involve Internet Explorer and hardware acceleration.  We've struggled to reproduce these problems on VMs and even one a physical Windows 7 machine, regardless of whether or not hardware acceleration is enabled.  In fact, the only machine we know of that has been able to reproduce these problems is a Dell Latitude E7440 with an Intel Integrated HD Graphics 4400 GPU (which belongs to @ToonTalk).

There are a number of things that give me qualms about devoting much effort to resolving this issue, including:

  * NLW doesn't run great in IE, to begin with
  * Our percentage of IE users is in the single digits
  * My suspicion is that there isn't really anything that we can realistically do about it
  * The problem does not appear to affect a large portion of the IE userbase (given that our only reports about it have come from a single source)
  * The problem does not appear to be present in IE's successor, Microsoft Edge
  * The problem can be worked around by turning off hardware acceleration
  * The problem can be worked around (for a much, much better user experience) by simply using a different browser

For these reasons, I'm going to create this issue and immediately close it as "won't fix", because I don't think I can justify devoting the time and resources to investigating and attempting to *maybe* fix this issue.

This ticket is being created simply for documentation/posterity, and to serve as a catch-all ticket for any future reports that stem from this problem.

Related issues: #257, #336

(#335 is also *possibly* related, but probably not.)

**Comment by ToonTalk** [comment]
That all makes sense.

I wonder if there is a way to document this somewhere for those few IE11 users (I only use it for testing but I have run across schools where IE is the only browser).
