### ISSUE TITLE
Compiler error in Chrome from ractive.js Computed properties without setters are read-only

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/Galapagos#339]
http://www.netlogoweb.org/web?http://m.modelling4all.org/p/9oJf503_AM446-E7xFl25g.nlogo

doesn't load

Chrome Version 49.0.2623.110 m - WIndows 7

It does load and run fine in FireFox.

Also no error is reported - instead the spinning logo stays up forever.

web:232 http://m.modelling4all.org/p/9oJf503_AM446-E7xFl25g.nlogo
ractive.js:423 Ractive.js 0.7.3 in debug mode, more...
ractive.js:455 Ractive.js: Failed to compute "hexColor"
ractive.js:459 TypeError: window.netlogoColorToHexString is not a function
    at window.RactiveLabel.RactiveWidget.extend.computed.hexColor (label.js:48)
    at Computation.get (ractive.js:13996)
    at Object.Viewmodel$get [as get] (ractive.js:14136)
    at Object.Mapping.getValue (ractive.js:14260)
    at Object.Viewmodel (ractive.js:14842)
    at initialiseRactiveInstance (ractive.js:15029)
    at createInstance (ractive.js:15340)
    at Object.Component$init [as init] (ractive.js:15455)
    at Object.Component (ractive.js:15548)
    at createItem (ractive.js:15770)
ractive.js:14030 Uncaught Error: Computed properties without setters are read-only. (This may change in a future version of Ractive!)

**Comment by TheBizzle** [comment]
Hmm... interesting.  I'm not seeing this when I open the page in Opera or Chrome.  However, it _would_ make sense in a lot of ways, since this error is related to some code that I recently deployed.  So I'm conflicted.  Can you try clearing cache or opening the page in a "private browsing" window and seeing if you still have the problem?

**Comment by ToonTalk** [comment]
Private browsing fixed the problem. Thanks.

I don't know if there is a way to deal with these cache problems in general. But perhaps some error handling would help since it looked as if it was just taking a very long time to load.

**Comment by TheBizzle** [comment]
> But perhaps some error handling would help since it looked as if it was just taking a very long time to load.

Ah, thanks for pointing that out.  I hadn't caught that.  I spun this issue off into #342, which has now been fixed.
