### ISSUE TITLE
Slider units displayed incorrectly

### ISSUE THREAD

**Issue by TheBizzle** [NetLogo/Galapagos#343]
_From @ToonTalk on May 1, 2016 16:11_

A slide with units

ᵒC

looks fine in the desktop version but looks like

![image](https://cloud.githubusercontent.com/assets/2138696/14942815/a3dc902e-0fbf-11e6-989b-100a9b43a552.png)

in the web version.

_Copied from original issue: NetLogo/Tortoise#181_

**Comment by TheBizzle** [comment]
The strange thing is... both ᵒ (your character) and ° (the proper degree symbol) display correctly for me in NLW.  Despite trying many, many things, I can't seem to find any way to reproduce what you're seeing.

Could you tell me what operating system and browser you're using when you see this?  Does it look the same to you in other browsers/on other machines?  Could I maybe see a copy of the model that's behaving like this?  Could you open your browser console and tell me what the value of `document.characterSet` is?

**Comment by ToonTalk** [comment]
Turns out this is caused by exporting to HTML. (I was looking at a student project and didn't realise that this was the case.)

Windows 7 - both Chrome and FireFox.

**Comment by TheBizzle** [comment]
Thanks, @ToonTalk.  Standalone HTML pages were the missing link there.

This problem won't be present in any new standalone pages generated from netlogoweb.org anymore.
