### ISSUE TITLE
NaN in plot

### ISSUE THREAD

**Issue by surfaslt** [NetLogo/Galapagos#350]
On-mouse-over plot says NaN even though the data is displayed in plot correctly. The same application does not have this problem when saved as "NetLogo Web". Please see the pictures.

![netlogoweb error](https://cloud.githubusercontent.com/assets/5831685/17146570/eaf63660-5356-11e6-8ebc-b69fe8c4fc7a.png)
![netlogo bug](https://cloud.githubusercontent.com/assets/5831685/17146569/eaf3f33c-5356-11e6-85d6-043c8ee3a492.JPG)

**Comment by TheBizzle** [comment]
Can you send a copy of the model, so I can reproduce the problem locally?

**Comment by surfaslt** [comment]
[pre-completed version for bruce v1.1.zip](https://github.com/NetLogo/Galapagos/files/384424/pre-completed.version.for.bruce.v1.1.zip)

**Comment by TheBizzle** [comment]
@surfaslt, this has now been fixed on netlogoweb.org (though you might need to clear your browser's cache before you see the changes take effect).
