### ISSUE TITLE
exporting values of chart to CSV

### ISSUE THREAD

**Issue by bquast** [NetLogo/Galapagos#352]
In addition to the ability to export graphics, it might be helpful to also be able to export the underlying values.

**Comment by CamdenClark** [comment]
I've been hacking on this. The issue with adding a "Download CSV" button is that you need to make significant changes to the Highcharts prototype. These would probably live in a file outside highchartsops.coffee.

We can take some significant cues from https://github.com/highcharts/export-csv.

**Comment by CamdenClark** [comment]
I did something a little different. See my PR here
https://github.com/NetLogo/Galapagos/pull/361
