### ISSUE TITLE
Anonymous procedure string representation differs from desktop NetLogo

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/Galapagos#358]
(word f) in the executable (6.0) produces a string like

"(anonymous command from: procedure GO-HOME-EVERY-DAY-00005: [SET-MY-DESTINATION-TO-HOME-00004])"

While in NetLogo Web it produces

"(anonymous command)"

This interferes with the ability of the Behaviour Composer to remove the appropriate function from a list. This can be programmed around however it will make the code more complex and slightly slower. Could the web version produce a similar string to what the executable does?

Presumably it would be useful for others for debugging.

**Comment by TheBizzle** [comment]
This issue was moved to NetLogo/Tortoise#183
