### ISSUE TITLE
Bar charts sometimes cut off leftmost bar

### ISSUE THREAD

**Issue by TheBizzle** [NetLogo/Galapagos#371]
A user writes:

> It looks like there is an error in the NetLogoWeb Bug Hunt Speeds. The purple bar (for the slowest bugs) does not appear in the histogram.

Upon investigation, it looks HighCharts is doing something weird with the calculations for how much spacing it should provide to the bars.  If the bars aren't spaced at all, they all display.  Once spacing is provided, things get weird.

**Comment by LaCuneta** [comment]
While a recent change in plot title sizes corrected Bug Hunt Speeds, I added a few more bars to its plot and confirmed this can still be an issue.  The updated model is attached.  

[Bug Hunt Speeds - bar plot issue.nlogo.zip](https://github.com/NetLogo/Galapagos/files/1267441/Bug.Hunt.Speeds.-.bar.plot.issue.nlogo.zip)
