### ISSUE TITLE
CoffeeScript error, any version mismatch?

### ISSUE THREAD

**Issue by yangboz** [NetLogo/Galapagos#374]
Using "scala-play-sbt:2.12.2-2.6.0-0.13.15", But got error as following:

/Galapagos-2.2.1/app/assets/javascripts/TortoiseJS/agent/component/widget.coffee:23: unexpected =
[error]     "*.updateWidgetValue": (_, { proxies = {}, triggers = {}, values = {}}) ->
[error]                                          ^
[error] one error found
[error] (web-assets:coffeescript) com.typesafe.sbt.web.CompileProblemsException
[info] CoffeeScript compiling on 1 source(s)
[error] /Users/smartkit/Downloads/Galapagos-2.2.1/app/assets/javascripts/TortoiseJS/agent/component/widget.coffee:23: unexpected =
[error]     "*.updateWidgetValue": (_, { proxies = {}, triggers = {}, values = {}}) ->
[error]                                          ^
[error] one error found
[error] (web-assets:coffeescript) com.typesafe.sbt.web.CompileProblemsException
[error] application - 

! @761gjaf3a - Internal server error, for (GET) [/] ->
 
play.sbt.PlayExceptions$CompilationException: Compilation error[unexpected =]
	at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27)
	at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27)
	at scala.Option.map(Option.scala:145)
	at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:49)
	at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:44)
	at scala.Option.map(Option.scala:145)
	at play.sbt.run.PlayReload$.taskFailureHandler(PlayReload.scala:44)
	at play.sbt.run.PlayReload$.compileFailure(PlayReload.scala:40)
	at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17)
	at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17)
[info] CoffeeScript compiling on 1 source(s)
[error] /Users/smartkit/Downloads/Galapagos-2.2.1/app/assets/javascripts/TortoiseJS/agent/component/widget.coffee:23: unexpected =
[error]     "*.updateWidgetValue": (_, { proxies = {}, triggers = {}, values = {}}) ->
[error]                                          ^
[error] one error found
[error] (web-assets:coffeescript) com.typesafe.sbt.web.CompileProblemsException
[info] CoffeeScript compiling on 1 source(s)
[error] /Users/smartkit/Downloads/Galapagos-2.2.1/app/assets/javascripts/TortoiseJS/agent/component/widget.coffee:23: unexpected =
[error]     "*.updateWidgetValue": (_, { proxies = {}, triggers = {}, values = {}}) ->
[error]                                          ^
[error] one error found
[error] (web-assets:coffeescript) com.typesafe.sbt.web.CompileProblemsException

**Comment by TheBizzle** [comment]
The SBT CoffeeScript plugin comes with an old version of CoffeeScript.  In your terminal, run `npm install` from the root of the repository to get the proper version of CoffeeScript installed.

**Comment by LaCuneta** [comment]
I added a note about this error to the [building and running wiki page](https://github.com/NetLogo/Galapagos/wiki/Building-and-running).  Let us know if you have more trouble with it.
