### ISSUE TITLE
plotxy misbehaves in NetLogo Web

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/Galapagos#389]
This use of plotxy simply draws a square

[phase space plot.zip](https://github.com/NetLogo/Galapagos/files/2720754/phase.space.plot.zip)

It works fine in the executable:

![image](https://user-images.githubusercontent.com/2138696/50592440-08f51300-0e8c-11e9-9f8f-8300cda8735d.png)

But in the web version the plot looks like:

![image](https://user-images.githubusercontent.com/2138696/50592472-25914b00-0e8c-11e9-9fc4-cf2a279c1607.png)

**Comment by LaCuneta** [comment]
Ken, thanks for submitting the issue and for the good sample model.  I've confirmed the problem and will see how difficult a fix looks.
