### ISSUE TITLE
tortoise_require is not defined--netlogoweb.org is down

### ISSUE THREAD

**Issue by mchen0037** [NetLogo/Galapagos#391]
![Capture](https://user-images.githubusercontent.com/31076823/81904263-e3941100-9577-11ea-8ee5-0eae37fd68e4.PNG)

Not sure if this is the right repository to put the issue in, but the web version has been broken for me for the past few hours. (Endless spinny loop)

**Comment by TheBizzle** [comment]
@mchen0037 What browser and version are you using?

**Comment by mchen0037** [comment]
Oof, was using an older laptop with the non-Chromium based version of Edge (not sure of version).

Everything works fine for me now, but maybe there should be support for that browser?

**Comment by LaCuneta** [comment]
Thanks for updating us, glad it wasn't a site issue!  When the non-Chromium Edge was receiving updates from Microsoft we did put in efforts to support it, but our usual policy is to target just the latest versions of Chrome (and derivatives like the new Edge), Safari, and Firefox given our limited developer resources.
