### ISSUE TITLE
Empty ID Manager / Undefined MessagePort

### ISSUE THREAD

**Issue by cs2027** [NetLogo/Galapagos#403]
See here for more details: https://github.com/NetLogo/Galapagos/blob/hostB-page-ui/app/assets/javascripts/beak/session-lite.coffee#L799

**Comment by TheBizzle** [comment]
Relevant only to the `hostB-page-ui` branch, for HubNet Web.

**Comment by TheBizzle** [comment]
Resolved in changes to `hostB-page-ui` branches in Galapagos and HubNet-Web repos.
