### ISSUE TITLE
Model Compilation Error (setup + go) after Command Center Usage

### ISSUE THREAD

**Issue by cs2027** [NetLogo/Galapagos#404]
Basically, if I do `setup + go`, it works okay on the first time, but then, if I run some commands in the (refactored) command center, `setup + go` no longer works (error with the `Turtle` object / specifically the `setShape(...)` function).

**Comment by TheBizzle** [comment]
Relevant only to the `hostB-page-ui` branch, for HubNet Web.

**Comment by TheBizzle** [comment]
Transferred to https://github.com/NetLogo/HubNet-Web/issues/21.
