### ISSUE TITLE
side-by-side Tortoise & Teletortoise UI with shared command center

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/Galapagos#41]
I think this would be fun/useful to have for testing/demo purposes. I'd type the same command once in the shared command center and then it would run in both T and TT and could eyeball whether the results were the same on both sides.

I might do a Swing version of this for doing similar Tortoise/NetLogo comparisons

(Jason suggested I open a ticket)

**Comment by TheBizzle** [comment]
This issue was moved to NetLogo/Teletortoise#10
