### ISSUE TITLE
Setting World Wrapping / NoWrapping

### ISSUE THREAD

**Issue by bytezen** [NetLogo/Galapagos#414]
There is no option for changing the topology for the world in NetLogoWeb like NetLogo. I am new to the NetLogo so I don't know if there is a primitive in the language to do this, but I was unable to find anything in the Programming Guide.

**Comment by LaCuneta** [comment]
@bytezen Thanks for your interest in NetLogo Web.  You can set world wrapping in NetLogo Web.  You need to enter Authoring Mode by clicking on the padlock icon in the upper-left of the model, then you can double-click or right-click the world view to edit the settings.  In the popup are the wrapping settings.  Here is the Authoring documentation:  https://netlogoweb.org/docs/authoring

There is a `__change-topology` primitive that can change the world wrapping settings as well from NetLogo code, and this does work in NetLogo Web.  The `__` means it's not a totally official feature, but it's been around for a while so it's pretty safe to use.  Here are those docs:  https://github.com/NetLogo/NetLogo/wiki/Unofficial-features#primitives

Feel free to leave a comment here if you have questions about either of those methods.

**Comment by bytezen** [comment]
Thanks LaCuneta!  Awesome work on NLWeb, BTW.
