### ISSUE TITLE
Improve netlogo command request-response protocol

### ISSUE THREAD

**Issue by qiemem** [NetLogo/Galapagos#45]
Currently, the protocol consists of sending a command to the server. You then get a response that contains either the output that would've been printed to the command center printed or an error. This response is not traceable back to the original request.

The protocol should support:

- Support for reporters.
- Tracing responses back to their original request. It should be the actual, unique request. So, it should be done on a unique id, not just the request contents. This is absolutely necessary for reporters.
- Distinct "error" and "success" response. Success responses should contain the reporter result / command output.
- Possibly separate "success" response types for reporters and commands. I don't think so though. I was originally envisioning this, so I don't want to discard it completely.
- Responses for `print ""` and `crt 5` should be distinguishable. I'm happy to use null for this, since we literally want to say "there was no output", but I could be persuaded otherwise (leave out the key entirely?). Some equivalent of `Option` would be cool, but seems like overkill.

**Comment by TheBizzle** [comment]
This issue was moved to NetLogo/Teletortoise#5
