### ISSUE TITLE
larger models crash Safari on iOS

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/Galapagos#98]
with the current code (running at http://ccl.northwestern.edu/tortoise/2013-10-25/) small models like Vants and Climate Change work, but bigger votes ones like Voting and Fire crash Safari hard

confirmed on netlogo-devel by Simone Gabbrielli that it isn't just my iPad doing this (he's on iOS 7 too)

**Comment by TheBizzle** [comment]
I think this issue properly belongs in NetLogo/Tortoise, so I'm going to close it as a duplicate of NetLogo/Tortoise#168
